create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, seller_name varchar(255), visited int4, primary key (id));
create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, seller_name varchar(255), visited int4, primary key (id));
create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, seller_name varchar(255), visited int4, primary key (id));
create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, seller_name varchar(255), visited int4, primary key (id));
INSERT INTO tb_sales(seller_name,visited,deals,amount,date) VALUES ('Barry Allen',121,67,18196.0,'2022-06-16');
INSERT INTO tb_sales(seller_name,visited,deals,amount,date) VALUES ('Logan',26,14,4255.0,'2022-06-14');
INSERT INTO tb_sales(seller_name,visited,deals,amount,date) VALUES ('Padme',55,42,13249.0,'2022-06-14');
INSERT INTO tb_sales(seller_name,visited,deals,amount,date) VALUES ('Padme',73,65,20751.0,'2022-06-10');
